---
all:
  children:
    rabbitmq:
      children:
        rmq_master:
          hosts:
            rmq01:
              ansible_host: 192.168.1.11
        rmq_slaves:
          hosts:
            rmq02:
              ansible_host: 192.168.1.12
            # rmq03:
            #   ansible_host: 192.168.1.13
      vars:
        ansible_user: ubuntu
        ansible_become: true
